# Generated by Django 2.2.6 on 2019-10-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('pwn_count', models.PositiveIntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HackMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Email')),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Hacks')),
            ],
        ),
    ]
